-- DB2 Table Creation Script for POMS_METER
-- Based on MID001.cobol structure and requirements

-- Drop existing table if it exists
DROP TABLE POMS_METER;

-- Create POMS_METER table
CREATE TABLE POMS_METER (
    CUSTOMER_ID   CHAR(12)      NOT NULL,
    METER_ID      CHAR(12)      NOT NULL PRIMARY KEY,
    PREV_READ     DECIMAL(6,0)  NOT NULL DEFAULT 0,
    CURR_READ     DECIMAL(6,0)  NOT NULL DEFAULT 0,
    CREATED_DATE  DATE          NOT NULL DEFAULT CURRENT_DATE,
    UPDATED_DATE  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index on CUSTOMER_ID for faster lookups
CREATE INDEX IDX_POMS_METER_CUSTID ON POMS_METER(CUSTOMER_ID);

-- Create trigger to automatically update the UPDATED_DATE when record is modified
CREATE TRIGGER TRG_POMS_METER_UPDATE
BEFORE UPDATE ON POMS_METER
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
BEGIN ATOMIC
    SET N.UPDATED_DATE = CURRENT_TIMESTAMP;
END;

-- Insert sample data for testing
INSERT INTO POMS_METER (CUSTOMER_ID, METER_ID, PREV_READ, CURR_READ) VALUES
('CUST00000001', 'MTR-2024-C001', 1000, 1050),
('CUST00000002', 'MTR-2024-C002', 2000, 2080),
('CUST00000003', 'MTR-2024-C003', 1500, 1525);

-- Commit the changes
COMMIT;

-- Verify table creation
SELECT * FROM POMS_METER;

-- Display table structure
DESCRIBE POMS_METER;
